services:
  app: 
    image: node:18-alpine
    command: sh -c "yarn install && yarn dev"
    ports: 
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app

  mysql:
      image: mysql:8.0
      volumes:
      - docker-mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: salvah
        MYSQL_DATABASE: docker

volumes:
  docker-mysql-data: